#!/bin/sh -e

IMAGE=claude-dev:latest
DOCKER_BUILDKIT=0 docker build -f Docker/Dockerfile -t ${IMAGE} Docker

VOLUME_NAME="in-container-home"

CODE_ROOT="$HOME/Code"
ABS_PATH="$(pwd)"
case "$ABS_PATH" in
    "$CODE_ROOT"/*) REL_PATH="${ABS_PATH#"$CODE_ROOT"/}" ;;
    *)              REL_PATH="${ABS_PATH#/}" ;;
esac
REPO_PATH="/home/develop/${REL_PATH}"

docker run --rm -v "${VOLUME_NAME}:/home/develop" ${IMAGE} \
    sh -c 'test -s /home/develop/.claude.json || echo "{}" > /home/develop/.claude.json'

docker run \
    -it \
    -e HOME=/home/develop \
    --mount type=volume,source="${VOLUME_NAME}",target=/home/develop \
    --mount type=bind,source="$(pwd)",target="${REPO_PATH}" \
    --workdir "${REPO_PATH}" \
    --rm ${IMAGE} "$@"
